name: sensorial
description: Provides sensor manipulation utilities
version: 0.0.1

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_sensors:
    git: https://github.com/enzo-santos/flutter_sensors.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
