name: sensorial
version: 1.0.0
description: Provides sensor manipulation utilities.
repository: https://github.com/beet-software/sensorial.git

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    androidPackage: cl.ceisufro.fluttersensors
    pluginClass: FlutterSensorsPlugin
