name: flutter_sensors
description: A flutter plugin to access the available sensors of the device.
version: 0.2.0
homepage: https://github.com/LJaraCastillo/flutter_sensors

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: cl.ceisufro.fluttersensors
    pluginClass: FlutterSensorsPlugin
